# Generated by Django 3.2.7 on 2021-10-31 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='text',
        ),
    ]
